### ISSUE TITLE
Add localization for French language

### ISSUE THREAD

**Issue by hummatli** [hummatli/MAHAds#1]
Project needs your help to add French language localization.

For translation:
- Fork project. 
- get <a href="https://github.com/hummatli/MAHAds/blob/master/MAHAds/mah-ads/src/main/res/values-fr/strings.xml"> /values-fr/strings.xml</a> and translate 
- commit
- merge with main project

or 

translate it and send to settarxan@gmail.com

Invitation to @farizaghayev

**Comment by farizaghayev** [comment]
Thanks for invitation and I did it.
